export enum errConstants {
  // For examples only
  ERR_CLIENT_NAME_EMPTY = 'ERR_CLIENT_NAME_EMPTY',
  ERR_CLIENT_CALLBACK_URL_EMPTY = 'ERR_CLIENT_CALLBACK_URL_EMPTY',
  ERR_CLIENT_DUPLICATED = 'ERR_CLIENT_DUPLICATED',
  // Used in current project
  ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND',
}
