export enum errConstants {
  // For examples only
  ERR_CLIENT_NAME_EMPTY = 'ERR_CLIENT_NAME_EMPTY',
  ERR_CLIENT_CALLBACK_URL_EMPTY = 'ERR_CLIENT_CALLBACK_URL_EMPTY',
  ERR_CLIENT_DUPLICATED = 'ERR_CLIENT_DUPLICATED',
  // Used in current project
  ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND',
  ERR_PRODUCT_NOT_FOUND = 'ERR_PRODUCT_NOT_FOUND',
  ERR_ALREADY_SUBSCRIBED = 'ERR_ALREADY_SUBSCRIBED',
  ERR_INVALID_PROMO_CODE = 'ERR_INVALID_PROMO_CODE',
  ERR_INVALID_DISCOUNT = 'ERR_INVALID_DISCOUNT',
  ERR_SUBSCRIPTION_NOT_FOUND = 'ERR_SUBSCRIPTION_NOT_FOUND',
  ERR_INVALID_CYCLE_TYPE = 'ERR_INVALID_CYCLE_TYPE',
  ERR_CONVERSION_ALREADY_PENDING = 'ERR_CONVERSION_ALREADY_PENDING',
  ERR_SAME_CYCLE_TYPE = 'ERR_SAME_CYCLE_TYPE',
  ERR_PAYMENT_FAILED = 'ERR_PAYMENT_FAILED',
  ERR_SUBSCRIPTION_ALREADY_CANCELLED = 'ERR_SUBSCRIPTION_ALREADY_CANCELLED',
  ERR_SUBSCRIPTION_REFUNDING = 'ERR_SUBSCRIPTION_REFUNDING',
  ERR_SUBSCRIPTION_NOT_IN_GRACE = 'ERR_SUBSCRIPTION_NOT_IN_GRACE',
  ERR_SUBSCRIPTION_ID_EMPTY = 'ERR_SUBSCRIPTION_ID_EMPTY',
  // Discount related errors
  ERR_DISCOUNT_NOT_FOUND = 'ERR_DISCOUNT_NOT_FOUND',
  ERR_DISCOUNT_NOT_APPLICABLE = 'ERR_DISCOUNT_NOT_APPLICABLE',
  ERR_DISCOUNT_EXPIRED = 'ERR_DISCOUNT_EXPIRED',
  // Promo code application errors
  ERR_PROMO_CODE_NOT_FOUND = 'ERR_PROMO_CODE_NOT_FOUND',
  ERR_ORDER_AMOUNT_INVALID = 'ERR_ORDER_AMOUNT_INVALID',
  ERR_PRODUCT_IDS_REQUIRED = 'ERR_PRODUCT_IDS_REQUIRED',
}
