export enum errConstants {
  // For examples only
  ERR_CLIENT_NAME_EMPTY = 'ERR_CLIENT_NAME_EMPTY',
  ERR_CLIENT_CALLBACK_URL_EMPTY = 'ERR_CLIENT_CALLBACK_URL_EMPTY',
  ERR_CLIENT_DUPLICATED = 'ERR_CLIENT_DUPLICATED',
  // Used in current project
  ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND',
  ERR_PRODUCT_NOT_FOUND = 'ERR_PRODUCT_NOT_FOUND',
  ERR_ALREADY_SUBSCRIBED = 'ERR_ALREADY_SUBSCRIBED',
  ERR_INVALID_PROMO_CODE = 'ERR_INVALID_PROMO_CODE',
  ERR_INVALID_DISCOUNT = 'ERR_INVALID_DISCOUNT',
  ERR_SUBSCRIPTION_NOT_FOUND = 'ERR_SUBSCRIPTION_NOT_FOUND',
}
